### ISSUE TITLE
Dashboard problem.

### ISSUE THREAD

**Issue by xTapG** [theADAMJR/1PG#1]
Hey, AdamJR you have done great work for your dashboard, but i faced one issue with it.

It works fine as expected i got in the page with all the servers the bot is in and when i click on a server the page just loads infinitely, even the app doesn't crash.

Please help!

**Comment by theADAMJR** [comment]
Please provide console logs, while you load the server, so I can help you solve the problem (`Ctrl + Shift + J`).

**Comment by xTapG** [comment]
Thank you for replying, I fixed it! I will be releasing my bot using it, do you allow me? If you do you will soon see it at https://icebot.tk :)
