### ISSUE TITLE
error in command-handler.js error is here const command = commands.get(name);   try {     await command?.execute(msg, ...args);   }   catch (error) {     await msg.channel.send(`⚠ ${error?.message ?? 'Unknown error.'}`);   }   return command; }

### ISSUE THREAD

**Issue by Wumpuspro** [theADAMJR/1PG#21]
try to fix the error
const command = commands.get(name);
  try {
    await command?.execute(msg, ...args);
  }
  catch (error) {
    await msg.channel.send(`⚠ ${error?.message ?? 'Unknown error.'}`);
  }
  return command;
}
(unexpected token at command?.execute(msg, ...args);

**Comment by theADAMJR** [comment]
NodeJS v14+ is required to run this code.
